### ISSUE TITLE
Turpentine throws a SimpleXML error.

### ISSUE THREAD

**Issue by cscd98** [danslo/hhvm#20]
Getting the following error, tested against current master as of today. I didn't get this error before the simplexml refactor.

I am loading the home page to my magento 1.13 website.

```
a:5:{i:0;s:53:"Call to a member function setParent() on a non-object";i:1;s:2451:"#0 /var/www/vhosts/magento-capistrano/releases/20131205114931/lib/Varien/Simplexml/Element.php(452): Varien_Simplexml_Element->extendChild()
#1 /var/www/vhosts/magento-capistrano/releases/20131205114931/lib/Varien/Simplexml/Element.php(452): Varien_Simplexml_Element->extendChild()
#2 /var/www/vhosts/magento-capistrano/releases/20131205114931/lib/Varien/Simplexml/Element.php(452): Varien_Simplexml_Element->extendChild()
#3 /var/www/vhosts/magento-capistrano/releases/20131205114931/lib/Varien/Simplexml/Element.php(452): Varien_Simplexml_Element->extendChild()
#4 /var/www/vhosts/magento-capistrano/releases/20131205114931/lib/Varien/Simplexml/Element.php(391): Varien_Simplexml_Element->extendChild()
#5 /var/www/vhosts/magento-capistrano/releases/20131205114931/lib/Varien/Simplexml/Config.php(600): Varien_Simplexml_Element->extend()
#6 /var/www/vhosts/magento-capistrano/releases/20131205114931/app/code/local/Nexcessnet/Turpentine/Model/Shim/Mage/Core/App.php(63): Varien_Simplexml_Config->extend()
#7 /var/www/vhosts/magento-capistrano/releases/20131205114931/app/code/local/Nexcessnet/Turpentine/Model/Observer/Esi.php(119): Nexcessnet_Turpentine_Model_Shim_Mage_Core_App->shim_addEventObserver()
#8 /var/www/vhosts/magento-capistrano/releases/20131205114931/app/code/core/Mage/Core/Model/App.php(1338): Nexcessnet_Turpentine_Model_Observer_Esi->loadCacheClearEvents()
#9 /var/www/vhosts/magento-capistrano/releases/20131205114931/app/code/core/Mage/Core/Model/App.php(1317): Mage_Core_Model_App->_callObserverMethod()
#10 /var/www/vhosts/magento-capistrano/releases/20131205114931/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent()
#11 /var/www/vhosts/magento-capistrano/releases/20131205114931/app/code/core/Mage/Core/Controller/Varien/Front.php(128): Mage::dispatchEvent()
#12 /var/www/vhosts/magento-capistrano/releases/20131205114931/app/code/core/Mage/Core/Model/App.php(749): Mage_Core_Controller_Varien_Front->init()
#13 /var/www/vhosts/magento-capistrano/releases/20131205114931/app/code/core/Mage/Core/Model/App.php(1094): Mage_Core_Model_App->_initFrontController()
#14 /var/www/vhosts/magento-capistrano/releases/20131205114931/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Model_App->getFrontController()
#15 /var/www/vhosts/magento-capistrano/releases/20131205114931/app/Mage.php(684): Mage_Core_Model_App->run()
#16 /var/www/vhosts/magento-capistrano/releases/20131205114931/index.php(112): Mage::run()
```

**Comment by danslo** [comment]
Hi, can you try with the latest changes? This problem should be fixed.

Of course feel free to re-open if it isn't!

**Comment by cscd98** [comment]
I've pulled down simplexml-refactor and recompiled hhvm but still get the error. I am using commit 49c42721b351581a54372c3b320832e300d3503d which is the latest. I am also unable to reopen? Thanks

**Comment by danslo** [comment]
@craigcarnell I'm assuming this is not a clean Magento install - and thus will make it very hard for me to debug. What happens when you disable the turpentine module?

**Comment by cscd98** [comment]
There is no error thrown with the module disabled. It is an existing install. We use Varnish in front of our web server (the plugin we use for magento is called turpentine which supports hole punching).

The plugin is available on github:

https://github.com/nexcess/magento-turpentine

The particular error is thrown in this line - at the extend function

```
public function shim_addEventObserver( $area, $eventName, $obsName,
            $type=null, $class=null, $method=null ) {
        $eventConfig = new Varien_Simplexml_Config();
        $eventConfig->loadDom( $this->_shim_getEventDom(
            $area, $eventName, $obsName, $type, $class, $method ) );
        $this->_shim_getConfig()->extend( $eventConfig, true );
        // this wouldn't work if PHP had a sane object model
        $this->_shim_getApp()->_events[$area][$eventName] = null;
        return $this;
    }
```

The function is called from:

```
public function loadCacheClearEvents( $eventObject ) {
        Varien_Profiler::start( 'turpentine::observer::esi::loadCacheClearEvents' );
        $events = Mage::helper( 'turpentine/esi' )->getCacheClearEvents();
        $appShim = Mage::getSingleton( 'turpentine/shim_mage_core_app' );
        foreach( $events as $ccEvent ) {
            $appShim->shim_addEventObserver( 'global', $ccEvent,
                'turpentine_ban_' . $ccEvent, 'singleton',
                'turpentine/observer_ban', 'banClientEsiCache' );
        }
        Varien_Profiler::stop( 'turpentine::observer::esi::loadCacheClearEvents' );
    }
```

**Comment by danslo** [comment]
Yeah I'm familiar with Turpentine, it's good to know the issue is related to that module.

I'll reopen this but I'll name it differently.

**Comment by danslo** [comment]
@craigcarnell I tested a clean install of Magento 1.8.1.0 (with sample data) + Turpentine. It's all working fine.

Unfortunately for you this means you'll have to do some debugging of your problem yourself, as I cannot reproduce it :(

**Comment by danslo** [comment]
Closing this because I have not been able to reproduce with turpentine on a clean install.

If you have some more information please reopen it.

**Comment by cscd98** [comment]
This appears to have gone away since your recent merge with upstream! Thanks.

**Comment by danslo** [comment]
Nice to hear. Have fun!

**Comment by cscd98** [comment]
Just wondering has your changes now been pushed upstream? (to facebooks hhvm repo)

**Comment by danslo** [comment]
Not yet. That might take a while.
